#! /bin/bash

cat << EOT >> ~/.bashrc
alias seq="sequelize"
alias seqg="sequelize model:generate"
alias seqm="sequelize db:migrate"
alias sequ="sequelize db:migrate:undo"
alias seqs="sequelize db:migrate:status"
alias sequ.="sequelize db:migrate:undo:all"
alias gcl="git clone"
alias gpl="git pull"
alias gps="git push"
alias gco="git checkout"
alias gcm="git add . && git commit -m"
alias gdl="git branch -d"
alias gdr="git push origin --delete"
alias garu="git remote add origin"
alias gcru="git remote set-url origin"
alias gvru="git remote -v"
alias +user="cd user"
alias +auth="cd auth"
alias +prof="cd professional"
alias +cont="cd contract"
alias +conf="cd conflict"
alias +appt="cd appointment"
alias ~user="cd ../user"
alias ~auth="cd ../auth"
alias ~prof="cd ../professional"
alias ~cont="cd ../contract"
alias ~conf="cd ../conflict"
alias ~appt="cd ../appointment"
alias tsc.="+auth && tsc && ~user && tsc && ~prof && tsc && ~cont && tsc && ~appt && tsc && ~conf && tsc && cd .."
alias launch="npm i && seq init"
alias seqm.="+auth && seqm && ~user && seqm && ~prof && seqm && ~cont && seqm && ~appt && seqm && ~conf && seqm && cd .."
alias seqs.="+auth && seqs && ~user && seqs && ~prof && seqs && ~cont && seqs && ~appt && seqs && ~conf && seqs && cd .."
alias sequ..="+appt && sequ && ~conf && sequ && ~cont && sequ && ~prof && sequ && ~user && sequ && ~auth && sequ && cd .."
EOT